plugins {
    id 'java-library'
    id 'maven-publish'
    id 'net.neoforged.moddev' version '2.0.112'
    id 'idea'
}

version = project.mod_version
group = project.maven_group

base {
	archivesName = project.archives_base_name
}

tasks.withType(JavaCompile).configureEach {it.options.release = 21}


repositories {
    maven {
        name = "FzzyMaven"
        url = "https://maven.fzzyhmstrs.me/"
    }
    maven {
        url = "https://thedarkcolour.github.io/KotlinForForge/"
    }
    mavenCentral()
}

dependencies {
    implementation "me.fzzyhmstrs:fzzy_config:${project.fzzy_config_version}"
}

neoForge {
    // Specify the version of NeoForge to use.
    version = project.neo_version

    runs {
        client {
            client()
        }
        server {
            server()
            programArgument '--nogui'
        }
    }

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
}

processResources {
	inputs.property "version", project.version

	filesMatching("neoforge.mods.toml") {
		expand "version": project.version
	}
}


java {
	// Loom will automatically attach sourcesJar to a RemapSourcesJar task and to the "build" task
	// if it is present.
	// If you remove this line, sources will not be generated.
	withSourcesJar()

}

jar {
	from("LICENSE") {
		rename { "${it}_${project.base.archivesName.get()}"}
	}
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}
